import { EventsApi } from '../interfaces/EventsApi';
import { LauncherEvent, normalizeLauncherEvent } from '../interfaces/LauncherEvent';

// wailsjs/runtime is generated by `wails build` — safe to import dynamically
async function getRuntime() {
  try {
    // @ts-ignore — generated at build time by wails
    const rt = await import('../wailsjs/runtime/runtime');
    return rt;
  } catch {
    return null;
  }
}

export class WailsEventsApi implements EventsApi {
  onLauncherEvent(cb: (event: LauncherEvent) => void): () => void {
    let cancelled = false;
    let cleanup: (() => void) | null = null;

    getRuntime().then((rt) => {
      if (cancelled) return;
      if (rt?.EventsOn) {
        rt.EventsOn('launcher:event', (data: unknown) => {
          cb(normalizeLauncherEvent(data));
        });
        cleanup = () => rt.EventsOff?.('launcher:event');
      } else {
        console.warn('[WailsEventsApi] wailsjs/runtime not available — falling back to window');
        const w = window as any;
        const eventsOn = w.runtime?.EventsOn ?? w.EventsOn;
        if (typeof eventsOn === 'function') {
          eventsOn('launcher:event', (data: unknown) => {
            cb(normalizeLauncherEvent(data));
          });
        } else {
          console.error('[WailsEventsApi] No EventsOn found — join events will not update UI');
        }
      }
    });

    return () => {
      cancelled = true;
      cleanup?.();
    };
  }
}
