export function EventsOn(eventName: string, callback: (data: any) => void): () => void;
export function EventsOnce(eventName: string, callback: (data: any) => void): () => void;
export function EventsOff(eventName: string, ...additionalEventNames: string[]): void;
export function EventsOffAll(): void;
export function EventsEmit(eventName: string, ...data: any[]): void;
export function LogPrint(message: string): void;
export function LogInfo(message: string): void;
export function LogWarning(message: string): void;
export function LogError(message: string): void;
export function WindowReload(): void;
export function WindowSetTitle(title: string): void;
export function Quit(): void;
