// Code generated by tools/gencontracts — DO NOT EDIT.
// Source: shared/contracts/*.schema.json

package sharedtypes

// ServerManifest (RFC-0030)
type ServerManifest struct {
	ServerID    string        `json:"serverId"`
	Version     string        `json:"version"`
	GameVersion string        `json:"gameVersion"`
	Mods        []ModEntry    `json:"mods"`
	LaunchArgs  []string      `json:"launchArgs,omitempty"`
	Profile     ProfileConfig `json:"profile"`
}

type ModEntry struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Version      string   `json:"version"`
	SHA256       string   `json:"sha256"`
	SizeBytes    int64    `json:"sizeBytes,omitempty"`
	WorkshopID   string   `json:"workshopId,omitempty"`
	DownloadURL  string   `json:"downloadUrl,omitempty"`
	Dependencies []string `json:"dependencies"`
	Optional     bool     `json:"optional,omitempty"`
}

type ProfileConfig struct {
	ProfileID    string            `json:"profileId,omitempty"`
	ModLoadOrder []string          `json:"modLoadOrder,omitempty"`
	Env          map[string]string `json:"env,omitempty"`
}

type ServerDescriptor struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	ManifestPath string `json:"manifestPath"`
	PlayerCount  int    `json:"playerCount,omitempty"`
	MaxPlayers   int    `json:"maxPlayers,omitempty"`
	Ping         int    `json:"ping,omitempty"`
}

type ServerRegistry struct {
	Servers []ServerDescriptor `json:"servers"`
}

func (m *ServerManifest) ProfileID() string {
	if m.Profile.ProfileID != "" {
		return m.Profile.ProfileID
	}
	return m.ServerID
}

// LauncherSettings (RFC-0036)
type LauncherSettings struct {
	GamePath              string `json:"gamePath,omitempty"`
	SteamCMDPath          string `json:"steamcmdPath,omitempty"`
	CachePath             string `json:"cachePath,omitempty"`
	ProfilesPath          string `json:"profilesPath,omitempty"`
	ConcurrentDownloads   int    `json:"concurrentDownloads,omitempty"`
	BandwidthLimitMbps    int    `json:"bandwidthLimitMbps,omitempty"`
	VerifyChecksum        bool   `json:"verifyChecksum,omitempty"`
}

// LauncherEvent (RFC-0022)
type LauncherEvent struct {
	Type      string                 `json:"type"`
	Timestamp int64                  `json:"timestamp"`
	SessionID string                 `json:"sessionId"`
	PackageID string                 `json:"packageId,omitempty"`
	Error     string                 `json:"error,omitempty"`
	Progress  *EventProgress         `json:"progress,omitempty"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
}

type EventProgress struct {
	Current int64 `json:"current"`
	Total   int64 `json:"total"`
	Percent int   `json:"percent"`
	Speed   int64 `json:"speed,omitempty"`
	ETA     int   `json:"eta,omitempty"`
}
