/**
 * Code generated by tools/gencontracts — DO NOT EDIT.
 * Source: shared/contracts/*.schema.json
 */

export interface ServerManifest {
  serverId: string;
  version: string;
  gameVersion: string;
  mods: ModEntry[];
  launchArgs?: string[];
  profile: ProfileConfig;
}

export interface ModEntry {
  id: string;
  name: string;
  version: string;
  sha256: string;
  sizeBytes?: number;
  workshopId?: string;
  downloadUrl?: string;
  dependencies: string[];
  optional?: boolean;
}

export interface ProfileConfig {
  profileId?: string;
  modLoadOrder?: string[];
  env?: Record<string, string>;
}

export interface ServerDescriptor {
  id: string;
  name: string;
  description?: string;
  manifestPath: string;
  playerCount?: number;
  maxPlayers?: number;
  ping?: number;
}

export interface ServerRegistry {
  servers: ServerDescriptor[];
}

export interface LauncherSettings {
  gamePath?: string;
  steamcmdPath?: string;
  cachePath?: string;
  profilesPath?: string;
  concurrentDownloads?: number;
  bandwidthLimitMbps?: number;
  verifyChecksum?: boolean;
}

export type LauncherEventType =
  | 'session.start'
  | 'session.complete'
  | 'mod.resolve.start'
  | 'mod.resolve.complete'
  | 'download.start'
  | 'download.progress'
  | 'download.complete'
  | 'install.start'
  | 'install.complete'
  | 'manifest.loaded'
  | 'manifest.failed'
  | 'launch.started'
  | 'launch.exited'
  | 'launch.failed'
  | 'error'
  | 'trace.updated'
  | 'cache.repair.start'
  | 'cache.repair.complete';

export interface EventProgress {
  current: number;
  total: number;
  percent: number;
  speed?: number;
  eta?: number;
}

export interface LauncherEvent {
  type: LauncherEventType;
  timestamp: number;
  sessionId: string;
  packageId?: string;
  error?: string;
  progress?: EventProgress;
  metadata?: Record<string, unknown>;
}

/** UI-facing settings (Wails binding shape) */
export interface Settings {
  gamePath: string;
  steamcmdPath: string;
  cacheLocation: string;
  profilesLocation: string;
  maxConcurrent: number;
  bandwidthLimit: number;
  verifyChecksum: boolean;
}

export function settingsFromLauncher(s: LauncherSettings): Settings {
  return {
    gamePath: s.gamePath ?? '',
    steamcmdPath: s.steamcmdPath ?? '',
    cacheLocation: s.cachePath ?? '',
    profilesLocation: s.profilesPath ?? '',
    maxConcurrent: s.concurrentDownloads ?? 3,
    bandwidthLimit: s.bandwidthLimitMbps ?? 0,
    verifyChecksum: s.verifyChecksum ?? true,
  };
}

export function settingsToLauncher(s: Settings): LauncherSettings {
  return {
    gamePath: s.gamePath,
    steamcmdPath: s.steamcmdPath,
    cachePath: s.cacheLocation,
    profilesPath: s.profilesLocation,
    concurrentDownloads: s.maxConcurrent,
    bandwidthLimitMbps: s.bandwidthLimit,
    verifyChecksum: s.verifyChecksum,
  };
}
