// gencontracts generates Go and TypeScript types from shared/contracts JSON Schemas.
// Run: go run ./tools/gencontracts
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func main() {
	root := workspaceRoot()

	goOut := filepath.Join(root, "libs", "sharedtypes", "types_gen.go")
	tsOut := filepath.Join(root, "apps", "launcher-ui", "frontend", "src", "contracts", "generated.ts")
	publicReg := filepath.Join(root, "apps", "launcher-ui", "frontend", "public", "registry")

	if err := os.MkdirAll(filepath.Dir(goOut), 0o755); err != nil {
		fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(tsOut), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(goOut, []byte(goSource), 0o644); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(tsOut, []byte(tsSource), 0o644); err != nil {
		fatal(err)
	}

	if err := syncRegistry(root, publicReg); err != nil {
		fatal(err)
	}

	fmt.Println("generated:", goOut)
	fmt.Println("generated:", tsOut)
	fmt.Println("synced registry ->", publicReg)
}

func syncRegistry(root, publicReg string) error {
	if err := os.MkdirAll(publicReg, 0o755); err != nil {
		return err
	}
	serversSrc := filepath.Join(root, "examples", "servers.json")
	serversDst := filepath.Join(publicReg, "servers.json")
	if err := copyFile(serversSrc, serversDst); err != nil {
		return err
	}
	// Copy referenced manifests into public/registry/manifests/
	manifestsDir := filepath.Join(publicReg, "manifests")
	if err := os.MkdirAll(manifestsDir, 0o755); err != nil {
		return err
	}
	copies := []struct{ src, dst string }{
		{filepath.Join(root, "fixtures", "manifests", "demo-survival.json"), filepath.Join(manifestsDir, "demo-survival.json")},
		{filepath.Join(root, "examples", "manifest-v1.json"), filepath.Join(manifestsDir, "server-1.json")},
	}
	for _, c := range copies {
		if err := copyFile(c.src, c.dst); err != nil {
			return err
		}
	}
	// Registry for browser uses manifestPath relative to /registry/
	patch, err := os.ReadFile(serversDst)
	if err != nil {
		return err
	}
	// Rewrite paths for static hosting
	replaced := string(patch)
	replaced = replaceAll(replaced, `"manifestPath": "fixtures/manifests/demo-survival.json"`, `"manifestPath": "manifests/demo-survival.json"`)
	replaced = replaceAll(replaced, `"manifestPath": "examples/manifest-v1.json"`, `"manifestPath": "manifests/server-1.json"`)
	return os.WriteFile(serversDst, []byte(replaced), 0o644)
}

func replaceAll(s, old, new string) string {
	for {
		i := findSub(s, old)
		if i < 0 {
			return s
		}
		s = s[:i] + new + s[i+len(old):]
	}
}

func findSub(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func workspaceRoot() string {
	if r := os.Getenv("PZ_LAUNCHER_ROOT"); r != "" {
		return r
	}
	cwd, _ := os.Getwd()
	dir := cwd
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return cwd
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

const goSource = `// Code generated by tools/gencontracts — DO NOT EDIT.
// Source: shared/contracts/*.schema.json

package sharedtypes

// ServerManifest (RFC-0030)
type ServerManifest struct {
	ServerID    string        ` + "`json:\"serverId\"`" + `
	Version     string        ` + "`json:\"version\"`" + `
	GameVersion string        ` + "`json:\"gameVersion\"`" + `
	Mods        []ModEntry    ` + "`json:\"mods\"`" + `
	LaunchArgs  []string      ` + "`json:\"launchArgs,omitempty\"`" + `
	Profile     ProfileConfig ` + "`json:\"profile\"`" + `
}

type ModEntry struct {
	ID           string   ` + "`json:\"id\"`" + `
	Name         string   ` + "`json:\"name\"`" + `
	Version      string   ` + "`json:\"version\"`" + `
	SHA256       string   ` + "`json:\"sha256\"`" + `
	SizeBytes    int64    ` + "`json:\"sizeBytes,omitempty\"`" + `
	WorkshopID   string   ` + "`json:\"workshopId,omitempty\"`" + `
	DownloadURL  string   ` + "`json:\"downloadUrl,omitempty\"`" + `
	Dependencies []string ` + "`json:\"dependencies\"`" + `
	Optional     bool     ` + "`json:\"optional,omitempty\"`" + `
}

type ProfileConfig struct {
	ProfileID    string            ` + "`json:\"profileId,omitempty\"`" + `
	ModLoadOrder []string          ` + "`json:\"modLoadOrder,omitempty\"`" + `
	Env          map[string]string ` + "`json:\"env,omitempty\"`" + `
}

type ServerDescriptor struct {
	ID           string ` + "`json:\"id\"`" + `
	Name         string ` + "`json:\"name\"`" + `
	Description  string ` + "`json:\"description,omitempty\"`" + `
	ManifestPath string ` + "`json:\"manifestPath\"`" + `
	PlayerCount  int    ` + "`json:\"playerCount,omitempty\"`" + `
	MaxPlayers   int    ` + "`json:\"maxPlayers,omitempty\"`" + `
	Ping         int    ` + "`json:\"ping,omitempty\"`" + `
}

type ServerRegistry struct {
	Servers []ServerDescriptor ` + "`json:\"servers\"`" + `
}

func (m *ServerManifest) ProfileID() string {
	if m.Profile.ProfileID != "" {
		return m.Profile.ProfileID
	}
	return m.ServerID
}

// LauncherSettings (RFC-0036)
type LauncherSettings struct {
	GamePath              string ` + "`json:\"gamePath,omitempty\"`" + `
	SteamCMDPath          string ` + "`json:\"steamcmdPath,omitempty\"`" + `
	CachePath             string ` + "`json:\"cachePath,omitempty\"`" + `
	ProfilesPath          string ` + "`json:\"profilesPath,omitempty\"`" + `
	ConcurrentDownloads   int    ` + "`json:\"concurrentDownloads,omitempty\"`" + `
	BandwidthLimitMbps    int    ` + "`json:\"bandwidthLimitMbps,omitempty\"`" + `
	VerifyChecksum        bool   ` + "`json:\"verifyChecksum,omitempty\"`" + `
}

// LauncherEvent (RFC-0022)
type LauncherEvent struct {
	Type      string                 ` + "`json:\"type\"`" + `
	Timestamp int64                  ` + "`json:\"timestamp\"`" + `
	SessionID string                 ` + "`json:\"sessionId\"`" + `
	PackageID string                 ` + "`json:\"packageId,omitempty\"`" + `
	Error     string                 ` + "`json:\"error,omitempty\"`" + `
	Progress  *EventProgress         ` + "`json:\"progress,omitempty\"`" + `
	Metadata  map[string]interface{} ` + "`json:\"metadata,omitempty\"`" + `
}

type EventProgress struct {
	Current int64 ` + "`json:\"current\"`" + `
	Total   int64 ` + "`json:\"total\"`" + `
	Percent int   ` + "`json:\"percent\"`" + `
	Speed   int64 ` + "`json:\"speed,omitempty\"`" + `
	ETA     int   ` + "`json:\"eta,omitempty\"`" + `
}
`

const tsSource = `/**
 * Code generated by tools/gencontracts — DO NOT EDIT.
 * Source: shared/contracts/*.schema.json
 */

export interface ServerManifest {
  serverId: string;
  version: string;
  gameVersion: string;
  mods: ModEntry[];
  launchArgs?: string[];
  profile: ProfileConfig;
}

export interface ModEntry {
  id: string;
  name: string;
  version: string;
  sha256: string;
  sizeBytes?: number;
  workshopId?: string;
  downloadUrl?: string;
  dependencies: string[];
  optional?: boolean;
}

export interface ProfileConfig {
  profileId?: string;
  modLoadOrder?: string[];
  env?: Record<string, string>;
}

export interface ServerDescriptor {
  id: string;
  name: string;
  description?: string;
  manifestPath: string;
  playerCount?: number;
  maxPlayers?: number;
  ping?: number;
}

export interface ServerRegistry {
  servers: ServerDescriptor[];
}

export interface LauncherSettings {
  gamePath?: string;
  steamcmdPath?: string;
  cachePath?: string;
  profilesPath?: string;
  concurrentDownloads?: number;
  bandwidthLimitMbps?: number;
  verifyChecksum?: boolean;
}

export type LauncherEventType =
  | 'session.start'
  | 'session.complete'
  | 'mod.resolve.start'
  | 'mod.resolve.complete'
  | 'download.start'
  | 'download.progress'
  | 'download.complete'
  | 'install.start'
  | 'install.complete'
  | 'manifest.loaded'
  | 'manifest.failed'
  | 'launch.started'
  | 'launch.exited'
  | 'launch.failed'
  | 'error'
  | 'trace.updated'
  | 'cache.repair.start'
  | 'cache.repair.complete';

export interface EventProgress {
  current: number;
  total: number;
  percent: number;
  speed?: number;
  eta?: number;
}

export interface LauncherEvent {
  type: LauncherEventType;
  timestamp: number;
  sessionId: string;
  packageId?: string;
  error?: string;
  progress?: EventProgress;
  metadata?: Record<string, unknown>;
}

/** UI-facing settings (Wails binding shape) */
export interface Settings {
  gamePath: string;
  steamcmdPath: string;
  cacheLocation: string;
  profilesLocation: string;
  maxConcurrent: number;
  bandwidthLimit: number;
  verifyChecksum: boolean;
}

export function settingsFromLauncher(s: LauncherSettings): Settings {
  return {
    gamePath: s.gamePath ?? '',
    steamcmdPath: s.steamcmdPath ?? '',
    cacheLocation: s.cachePath ?? '',
    profilesLocation: s.profilesPath ?? '',
    maxConcurrent: s.concurrentDownloads ?? 3,
    bandwidthLimit: s.bandwidthLimitMbps ?? 0,
    verifyChecksum: s.verifyChecksum ?? true,
  };
}

export function settingsToLauncher(s: Settings): LauncherSettings {
  return {
    gamePath: s.gamePath,
    steamcmdPath: s.steamcmdPath,
    cachePath: s.cacheLocation,
    profilesPath: s.profilesLocation,
    concurrentDownloads: s.maxConcurrent,
    bandwidthLimitMbps: s.bandwidthLimit,
    verifyChecksum: s.verifyChecksum,
  };
}
`
